### PR TITLE
specific patterns must be analysed first to prevent false positives.

### PR DESCRIPTION
**Pull request by danielmedina**
## Summary

I changed the pattern's order to analyse more specific rules (in my case, elo rules) first.

## Motivation

When your library analyse credit card patterns, it stops at first match. In my case, using elo bins, some numbers was identificated as maestro cards. I will attach all the bins used by elo in Brazil.

## Testing

You alread had elo tests. I created two fiddles to test this solution with my bin list.

This is with your library nowadays -> https://jsfiddle.net/nd3o81uq/3/
This is with my modifications, in my fork ->  https://jsfiddle.net/ay2rgoua/

Attached file -> all elo Bins used in Brazil
[elo_rangebinsproduto.pdf](https://github.com/stripe/jquery.payment/files/261407/elo_rangebinsproduto.pdf)

### CODE REVIEW

**Comment by jenanwise** [comment]
@danielmedina This change looks good, but I'll take care of incrementing versions separately. Can you make this PR just 1 commit w/o the version changes? Thanks!

**Comment by danielmedina** [comment]
You can ignore the increment version part. I didn't know that whill appear on pull request. 
Sorry about my delay. Github didn't warn me about your answer.

**Comment by jenanwise** [comment]
@danielmedina If you use `git rebase` you can change your branch locally and then `git push --force` to cleanup this PR. Please let me know when you do!

**Comment by danielmedina** [comment]
Use the other pull request... I can't do what you sugest.

**Comment by danielmedina** [comment]
The other pull request have the things you want?

**Comment by jenanwise** [comment]
Yup! Merged it.

**Pull request closed without merging**
