### PR TITLE
Updated the ReadMe file to include knockout.js and Durandal.js databindings.

### PR DESCRIPTION
**Pull request by mbejda**
Updated the ReadMe file to include knockout.js and Durandal.js databindings.

### CODE REVIEW

**Comment by thbar** [comment]
@mbejda thanks for sharing, this is useful. If this doesn't get included into the readme, maybe worth including in the examples at least.

**Comment by SlexAxton** [comment]
Thanks for bumping this @thbar and thanks for the examples @mbejda !

I'd love for information like this to be easier for everyone to find, but it's hard to merge stuff like this when we don't have anyone who knows these frameworks well, internally (they get out of date and we can't test the changes). Additionally, I'd guess we'd have to start putting a *lot* more frameworks into the readme (everyone's favorite some-way-bound m-v-* microlib module framework system).

As a halfway point, how would you guys feel about a section called "Framework Integrations" that just links out to a personal repo or a gist that you're willing to keep up to date?

If that sounds agreeable, I'm happy to take that pull request.

Thanks!

**Comment by thbar** [comment]
@SlexAxton as a regular KnockOut user, I wouldn't expect you to test the bindings! Just a mention of the tested version alongside with the code would be good enough (people are usually tweaking the bindings or similar usually anyway), as well as a note at the top to indicate that the integrations may be out of date, provided by users etc.

Maybe having a framework integrations section with the full code will make it easier for someone to update a broken integration via a PR? Otherwise links to gist will work too, maybe a bit harder to update over the long run!

**Comment by jamesreggio** [comment]
I agree with @SlexAxton that links to Gists would be preferable.

**Comment by jamesreggio** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
