### PR TITLE
Another Stab At Fixing The Cursor Jumping Issue

### LINKED ISSUE #121: Cursor jump when correcting
If you already entered a number and click into the field to correct one digit, the cursor is moving to the end of the card number after you hit backspace. This affect should be avoided.

### PR DESCRIPTION
**Pull request by rovermicrover**
I went off #148 by narkeeso, which was trying to fix #121. I took his logic, put it in it's own method, reversed the order so value is set then cursor position is updated. Also, selectionStart, and selectionEnd are both set to stop highlighting of characters on paste. This way I was able to add the new logic to reFormatNumeric without poor results, and remove the blacklist.

This seems to work on my end, and passes tests on my local, but some feedback would be appreciated.

### CODE REVIEW

**Comment by rovermicrover** [comment]
Added a commit that fixes a few related issues. 

Not all inputs support the property 'selectionStart', so added a try catch for them on finding cursor position.

If someone filled out one input very quickly, tabbed to the next the update cursor event could fire after they where to the next input, which means they would focus back to the pervious input. So, added a check to make sure before cursor set that $target is focused.

**Comment by domi55** [comment]
@jamesreggio what do you think?

**Comment by karlatkinson** [comment]
Any update on this?

**Comment by jamesreggio** [comment]
@rovermicrover, thank you for this.

This solution is not perfect cross-platform, but it certainly helps the 80% case.

Because this is difficult to test, I'm going to update the minor version for this (so people have some sense that it may regress them).

**Comment by rovermicrover** [comment]
What platforms are you seeing issues on? I am still actively working on related issues on our application.

**Comment by jamesreggio** [comment]
I'm not seeing issues, per se, but I can tell you that `selectionStart` is only supported beginning in IE9.

http://help.dottoro.com/ljtfkhio.php

**Comment by rovermicrover** [comment]
Ah, our IE9 support strategy is that if it works it only works by accident, so anything pre IE9 was far from my mind. So, I was working from that perspective. I can review everything and submit new commits based on keeping wider browser support in mind. What IE versions are supported, and are opera, opera-mini, and android stock browsers all supported?

**Comment by jamesreggio** [comment]
I wouldn't prioritize < IE9. The cursor-jumping issue is a nuisance, but not a blocker, so it's fine to not fix it for older versions of IE. In fact, I would recommend _against_ fixing it, since it would likely just add another layer of scar tissue to this library.

**Pull request merged**
