### PR TITLE
UMD

### PR DESCRIPTION
**Pull request by barvian**

### CODE REVIEW

**Comment by jamesreggio** [comment]
I'm curious why you feel it is acceptable to drop support for Zepto.

**Comment by mbarvian** [comment]
Not acceptable per sé; I just didn't know how to make it compatible with UMD factory methods.

**Comment by mbarvian** [comment]
Zepto support back in "global" environments.

**Comment by jenanwise** [comment]
Hi @barvian. My inclination is to not add support for UMD. The javascript module ecosystem is quite broad and rapidly changing, and we'd like to keep maintenance minimal where possible. E.g., it looks like the blessed way to write jquery plugins in umd [has changed](https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js) quite recently.

In general, we're also much less likely to accepts PRs without an accompanying written description, motivation, and references.

**Pull request closed without merging**
