### PR TITLE
Added NPM installation instructions

### PR DESCRIPTION
**Pull request by montogeek**

### CODE REVIEW

**Comment by jamesreggio** [comment]
Sorry, I don't believe this is necessary.

**Comment by montogeek** [comment]
Why not?

**Comment by jamesreggio** [comment]
It's like saying that the name of the repo is the name of the NPM package (which is also the name of the Bower package and the name of the jQuery plugin). Other than that, it's just instructing (without context) on how to run the most common `npm` command, which is also not really the purpose of the README.

**Comment by montogeek** [comment]
It's ok. Thanks! :)

**Pull request closed without merging**
