### PR TITLE
Update supported Elo's IINs

### PR DESCRIPTION
**Pull request by dcarral**
## Summary

Update supported Elo's IINs

## Motivation

Implement issue #221

## Testing

Added a couple of new cases to the existing test suite

### CODE REVIEW

**Comment by dcarral** [comment]
@jenanwise Due to the nature of Elo IIN ranges, I'm afraid of the impact on performance provoked by the huge list of substrings to check against.

How do you guys see it?

Is substituting the current substring comparison with a regex test something that you'd be happy about? I could work on that.

**Comment by jenanwise** [comment]
@dcarral We actually had regexes before and it was a pain to maintain. I think if you just limit to 3-digit suffixes it should be cleaner. None of the prefixes except `506` conflict with other prefixes, and that one can be 4-digits.

**Comment by dcarral** [comment]
@jenanwise Makes sense ;) 

I've just pushed an updated IIN list trying to keep a fair balance between simplification and correctness. Maintaining some of them in the full-digit form should help for future updates to other credit card types' IINs.

**Comment by jenanwise** [comment]
I squashed your commits and shortened the list in #223. I also cut a release. Thanks for contributing!

**Pull request closed without merging**
