### PR TITLE
Fixes cursor from jumping on reformat functions

### PR DESCRIPTION
**Pull request by narkeeso**
Fixes issue #121 - Cursor jump when correcting

### CODE REVIEW

**Comment by nilssolanki** [comment]
@narkeeso thank you very much for the fix. There is just one small issue with the expiry:
If I have entered 4 digits eg. "05 / 15" and I move my cursor back to right after the zero "0**|**5 / 15" and hit the backspace key to delete the zero, the cursor still jumps back to the end of the field again "05 / 15**|**"

**Comment by holic** [comment]
:+1:

**Comment by gpbmike** [comment]
For the love of all that is holy accept this PR.

**Comment by tomsommer** [comment]
+1

**Comment by Nirazul** [comment]
+1

**Comment by domi55** [comment]
+1

**Comment by jamesreggio** [comment]
I'm sorry about the delay, but there are a couple of problems with this PR:

* It removes the call to update the input value for the 'blacklisted' events. The purpose of the `reFormat...` series of methods is to support mobile devices that do properly emit `key(down|up)` events by performing a complete reformat of the input upon upon every `(change|input)` event. (It also serves to handle `paste` events.)

* It doesn't address the `reFormatNumeric` case, which is probably just an oversight.

Please @mention me when you push a fix to address these two concerns.

**Comment by domi55** [comment]
@narkeeso what do you think about the concerns mentioned by @jamesreggio

**Comment by narkeeso** [comment]
@domi55 Sorry for delayed response, I haven't had time to address the concerns mentioned above but haven't ran into the issues mentioned in practice.

**Comment by jamesreggio** [comment]
@narkeeso, thanks for the help here, too!

**Comment by narkeeso** [comment]
Awesome, glad I could help :)

**Pull request merged**
