### PR TITLE
Better expiry formatters

### PR DESCRIPTION
**Pull request by kulte**
### Better expiry formatters

Sometimes people have separate credit card input fields for month expiry and year expiry. There should exist library functionality to format these too.
- Added `$.fn.payment('formatMonthExpiry')` that includes a leading zero for single character inputs
- Added `$.fn.payment('formatTwoDigitYearExpiry')` that restricts length of input to two numeric characters
- Added `$.fn.payment('formatFourDigitYearExpiry')` that restricts length of input to four numeric characters

### CODE REVIEW

**Comment by montogeek** [comment]
Please merge this. As @mikemaccana said, even Stripe recommends to have two different inputs for expiration date.

**Comment by tomsommer** [comment]
+1

**Comment by robincwillis** [comment]
+1

**Comment by jenanwise** [comment]
Hey folks! Sorry for the lack of response here. It's not yet properly documented, but as you can see in the discussion in #160, `Stripe.js` now supports the combined month + day expiry.

We'd like to keep the api surface of `jquery.payment` as constrained as possible, so I'm going to close this PR. If you can do so, we do think a combined date month + day is the way to go (Stripe Checkout uses such a combined input).

**Comment by espen** [comment]
Perhaps I misunderstood discussion in #160 but I don't see any changes relating to this issue?

I'm still a bit confused with the title of this project: "A general purpose library for building credit card forms, validating inputs and formatting numbers." when this PR is closed because it doesn't follow the practice of stripe.js. I understand that the needs of Stripe in this project but as most other credit card forms are using two fields I find it 'opinionated' to put it mildly by not including support for two fields. Sorry if this comes out as passive-aggresive I'm just honestly a bit confused by the goal of the project. I use this in production and for it's a very nice helper lib and it's not very problematic with the lack of formatting for two expiry fields but it would be an improvement if it was there.

btw would love to see some studies that shows that a single field is better. One problem I see with Stripe checkout is that when a value is entered the placeholder is removed thus the user is unable to see what format is required.

**Comment by jpantarotto** [comment]
I realize that jquery.payment is now deprecated but another use case for separated validation of expiration fields came up for me recently.  Safari does not properly autofill CC info for the combined field and needed separate inputs in order to populate for saved CC's.

**Pull request closed without merging**
